baseURL = 'https://supernova.pet/'
languageCode = 'en-gb'
title = 'SuperNova Pet Care'
theme = 'pastel-nova'

disableKinds = ['taxonomy', 'term']

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[caches]
  [caches.getjson]
    maxAge = '1h'
